# File: templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
data:
  # Base64-encoded values
  POSTGRESQL_USER: {{ .Values.secret.POSTGRESQL_USER |   b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.secret.POSTGRESQL_PASSWORD | b64enc }}

