# deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }} 
      protocol: TCP
      name: http 
  selector:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}