{{- if .Values.spec.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-v2
spec:
  minAvailable: {{ .Values.spec.minAvailable }}
  maxUnavailable: {{ .Values.spec.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
{{- end }}
